# MODELAMIENTO

El dataset que usaremos en primera instancia sera el data set 6

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

In [4]:
df = pd.read_csv('dataset6.csv')
df.head()

,temperatura,sensacion_termica,humedad,velocidad_viento,total_alquileres,temporada_1,temporada_2,temporada_3,temporada_4,anio_0,...,dia_semana_3.0,dia_semana_4.0,dia_semana_5.0,dia_semana_6.0,dia_trabajo_0,dia_trabajo_1,clima_1,clima_2,clima_3,clima_4
0,0.24,0.2879,0.81,0.0,16.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1,0.22,0.2727,0.80,0.0,40.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
2,0.22,0.2727,0.80,0.0,32.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
3,0.24,0.2879,0.75,0.0,13.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
4,0.24,0.2879,0.75,0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0

Realizar las transformaciones respectivas, usar standardScaler, minMaxScaler, entre otros